package com.martijndashorst.euler;

import org.hamcrest.CoreMatchers;
import org.junit.Assert;
import org.junit.Test;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 */
public class Euler2 {
	@Test
	public void solution() {
		long sum = 0;
		long fibonacci = 1;
		long previous = 1;
		while (fibonacci < 4_000_000) {
			long tmp = previous;
			previous = fibonacci;
			fibonacci = fibonacci + tmp;

			if (fibonacci % 2 == 0)
				sum += fibonacci;
		}
		Assert.assertThat(sum, CoreMatchers.is(4_613_732L));
	}
}
